name: TfSec Security Scan

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  pull_request:
    branches:
      - main

jobs:
  tfsec-scan:
    name: Security Scan with TfSec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -O /usr/local/bin/tfsec
          chmod +x /usr/local/bin/tfsec

      - name: Check tfsec version
        run: tfsec --version

      - name: Run tfsec scan
        run: |
          cd infra
          tfsec --format=pretty . || true 


      - name: Upload tfsec results
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-results
          path: infra/tfsec-results.json
