name: TfSec Security Scan

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  pull_request:
    branches:
      - main

jobs:
  tfsec-scan:
    name: Security Scan with TfSec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TfSec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -O /usr/local/bin/tfsec
          chmod +x /usr/local/bin/tfsec

      - name: List files to confirm Terraform files exist
        run: |
          echo "Listing files in infra/"
          ls -R infra/

      - name: Run TfSec scan (Show results in GitHub Actions)
        run: |
          cd infra
          tfsec --format default . || true

